
# server
server:
  port: 8082
  servlet:
    contextPath: /application


# security
crypt:
  round: 10

security:
  jwt:
    token:
      key: helloworld

# db
database:
  hibernate:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.clcrffoai45i.us-east-1.rds.amazonaws.com/application_db
    username: application_user
    password: password
    dialect: org.hibernate.dialect.MySQLDialect
    showsql: false


# actuator
management:
  endpoints:
    web:
      exposure:
        include: health, beans, mappings, info, env

    health:
      showDetails: ALWAYS

  info:
    env:
      enabled: true
    app:
      name: application service
      description:
      version: 1.0.0


spring:
  application:
    name: application-service
  # for swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # rabbitmq
  rabbitmq:
    host: 54.88.238.139
    username: guest
    password: guest
    port: 5672

#eureka client
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
