# server
server:
  port: 8085
  servlet:
    context-path: /composite

# security
crypt:
  round: 10

security:
  jwt:
    token:
      key: helloworld


# actuator
management:
  endpoints:
    web:
      exposure:
        include: health, beans, mappings, info, env

    health:
      showDetails: ALWAYS

  info:
    env:
      enabled: true
    app:
      name: composite service
      description:
      version: 1.0.0


spring:

  # for swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  application:
    name: composite-service

  # rabbitmq
  rabbitmq:
    host: 54.88.238.139
    username: guest
    password: guest
    port: 5672

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


