server:
  port: 8081
  servlet:
    context-path: /employee-service


spring:
  application:
    name: employee-service
  data:
    mongodb:
      uri: mongodb+srv://employee_user:mongopassword@cluster0.hzayn.mongodb.net/ehr?retryWrites=true&w=majority
    config:
      import: optional:configserver:http://localhost:8012

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
