#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: >-
#      jdbc:mysql://database-1.clcrffoai45i.us-east-1.rds.amazonaws.com/housing_db
#    username: housing_user
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
##        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


database:
  hibernate:
    url: 'jdbc:mysql://database-1.clcrffoai45i.us-east-1.rds.amazonaws.com/housing_db'
    driver: com.mysql.cj.jdbc.Driver
    username: 'housing_user'
    password: 'password'
    dialect: org.hibernate.dialect.MySQLDialect
    showsql: true


spring:
  application:
    name: housing-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8083
  servlet:
    context-path: /housing-service



eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, beans, mappings, info, env
